version: '3.9'
services:
  web:
    image: cs353project
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: python app.py -u
  db:
    image: mysql:5.7
    environment:
      PYTHONUNBUFFERED: 1
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
